//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WyposazenieDlaSilowni
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zamowienia
    {
        public int ID { get; set; }
        public int Produkt { get; set; }
        public System.DateTime DataZlozeniaZamowienia { get; set; }
        public int Klient { get; set; }
    
        public virtual Klienci Klienci { get; set; }
        public virtual Produkty Produkty { get; set; }
    }
}
